<?php

declare(strict_types=1);

namespace App\Services\Tenant;

use App\Models\Tenant\Brand;
use App\Support\QueryFilter;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * Tenant product brand records and queries.
 *
 * Encapsulates all business logic for brand management, including
 * creation, updates, pagination, filtering, deletion, restoration,
 * product unlinking, and KPI metrics.
 *
 * Deletion is blocked when the brand is active.
 */
class BrandService
{
    /**
     * Get paginated brand records with eager loaded relations.
     *
     * @param int $perPage Number of records per page.
     * @param string|null $search Optional search term.
     * @param mixed $isActive Active/inactive filter tokens.
     * @param mixed $trashed Soft-delete filter tokens (only, with).
     *
     * @return LengthAwarePaginator<int, Brand>
     */
    public function getPaginated(
        int $perPage = 15,
        ?string $search = null,
        mixed $isActive = null,
        mixed $trashed = null,
    ): LengthAwarePaginator {
        return Brand::query()
            ->with(['logoMedia'])
            ->withCount('products')
            ->search($search)
            ->filterIsActive(QueryFilter::filterList($isActive))
            ->filterTrashed(QueryFilter::filterList($trashed))
            ->orderBy('sort_order')
            ->orderBy('name')
            ->paginate($perPage);
    }

    /**
     * Find brand by ID or fail with eager loaded relations.
     *
     * @param int $id Record identifier.
     *
     * @return Brand
     */
    public function findOrFail(int $id): Brand
    {
        return Brand::query()
            ->with(['logoMedia'])
            ->withCount('products')
            ->findOrFail($id);
    }

    /**
     * Create a new brand.
     *
     * Slug is auto-generated by Spatie Sluggable from the name field.
     *
     * @param array<string, mixed> $data
     *
     * @return Brand
     */
    public function create(array $data): Brand
    {
        return Brand::query()->create($data);
    }

    /**
     * Update brand.
     *
     * @param Brand $brand The model instance to update.
     * @param array<string, mixed> $data Attribute data to persist.
     *
     * @return Brand
     */
    public function update(Brand $brand, array $data): Brand
    {
        $brand->update($data);

        return $brand->fresh(['logoMedia']);
    }

    /**
     * Delete a single brand.
     *
     * Deletion is blocked if the brand is active.
     *
     * @param Brand $brand The model instance to delete.
     *
     * @return bool
     *
     * @throws ValidationException
     */
    public function delete(Brand $brand): bool
    {
        $this->assertBrandNotActive($brand);
        $this->assertBrandNotLinkedToProducts($brand);

        return $brand->delete();
    }

    /**
     * Delete multiple brands by ID.
     *
     * Deletion is blocked for any active brands in the set.
     *
     * @param list<int> $ids
     *
     * @return int Number of deleted records.
     *
     * @throws ValidationException
     */
    public function deleteMany(array $ids): int
    {
        $this->assertBrandsNotActive($ids);
        $this->assertBrandsNotLinkedToProducts($ids);

        return DB::transaction(function () use ($ids): int {
            $records = Brand::query()->whereIn('id', $ids)->get();
            $deleted = 0;

            foreach ($records as $record) {
                if ($record->delete()) {
                    $deleted++;
                }
            }

            return $deleted;
        });
    }

    /**
     * Restore a soft-deleted brand.
     *
     * @param int $id Trashed record identifier.
     *
     * @return Brand
     */
    public function restore(int $id): Brand
    {
        $model = Brand::withTrashed()->findOrFail($id);
        $model->restore();

        return $model->load(['logoMedia']);
    }

    /**
     * Restore multiple soft-deleted brands by ID.
     *
     * @param list<int> $ids
     *
     * @return int Number of restored records.
     */
    public function restoreMany(array $ids): int
    {
        return DB::transaction(function () use ($ids): int {
            $records = Brand::withTrashed()->whereIn('id', $ids)->get();
            $restored = 0;

            foreach ($records as $record) {
                if ($record->restore()) {
                    $restored++;
                }
            }

            return $restored;
        });
    }

    /**
     * Unlink all products from a brand.
     *
     * @param Brand $brand The brand to unlink products from.
     *
     * @return int Number of unlinked products.
     */
    public function unlinkProducts(Brand $brand): int
    {
        return $brand->products()->update(['brand_id' => null]);
    }

    /**
     * Unlink all products from multiple brands.
     *
     * @param list<int> $ids
     *
     * @return int Number of unlinked products.
     */
    public function bulkUnlinkProducts(array $ids): int
    {
        return Brand::query()
            ->whereIn('id', $ids)
            ->get()
            ->sum(fn (Brand $brand): int => $this->unlinkProducts($brand));
    }

    /**
     * Toggle the active status of a brand.
     *
     * @param Brand $brand The model instance to toggle.
     *
     * @return Brand
     */
    public function toggleActive(Brand $brand): Brand
    {
        $brand->update(['is_active' => ! $brand->is_active]);

        return $brand->fresh(['logoMedia']);
    }

    /**
     * Get only active brands.
     *
     * @return Collection<int, Brand>
     */
    public function getActive(): Collection
    {
        return Brand::query()
            ->where('is_active', true)
            ->orderBy('sort_order')
            ->orderBy('name')
            ->get();
    }

    /**
     * Get active brands as value/label pairs for select inputs.
     *
     * @return list<array{value: int, label: string}>
     */
    public function getOptions(): array
    {
        return Brand::query()
            ->where('is_active', true)
            ->orderBy('sort_order')
            ->orderBy('name')
            ->get()
            ->map(fn (Brand $brand): array => [
                'value' => $brand->id,
                'label' => $brand->name,
            ])
            ->values()
            ->all();
    }

    /**
     * KPI card metrics for brands.
     *
     * @return list<array{key: string, label: string, value: int}>
     */
    public function getMetrics(): array
    {
        $total = Brand::query()->count();
        $active = Brand::query()->where('is_active', true)->count();
        $inactive = Brand::query()->where('is_active', false)->count();
        $withLogo = Brand::query()->whereNotNull('logo_media_id')->count();

        return [
            ['key' => 'total', 'label' => 'Total Brands', 'value' => $total],
            ['key' => 'active', 'label' => 'Active', 'value' => $active],
            ['key' => 'inactive', 'label' => 'Inactive', 'value' => $inactive],
            ['key' => 'with_logo', 'label' => 'With Logo', 'value' => $withLogo],
        ];
    }

    /**
     * Ensure a brand is not active before deletion.
     *
     * @param Brand $brand
     *
     * @throws ValidationException
     */
    private function assertBrandNotActive(Brand $brand): void
    {
        if (! $brand->is_active) {
            return;
        }

        throw ValidationException::withMessages([
            'brand' => [
                "Cannot delete \"{$brand->name}\" because it is currently active. Deactivate it first.",
            ],
        ]);
    }

    /**
     * Ensure none of the given brands are active.
     *
     * @param list<int> $ids
     *
     * @throws ValidationException
     */
    private function assertBrandsNotActive(array $ids): void
    {
        $activeBrands = Brand::query()
            ->whereIn('id', $ids)
            ->where('is_active', true)
            ->get();

        if ($activeBrands->isEmpty()) {
            return;
        }

        $names = $activeBrands
            ->map(static fn (Brand $brand): string => "\"{$brand->name}\"")
            ->implode(', ');

        throw ValidationException::withMessages([
            'ids' => [
                "Cannot delete active brands: {$names}. Deactivate them first.",
            ],
        ]);
    }

    /**
     * Ensure a brand is not linked to any products before deletion.
     *
     * @param Brand $brand
     *
     * @throws ValidationException
     */
    private function assertBrandNotLinkedToProducts(Brand $brand): void
    {
        $count = $brand->products()->count();

        if ($count === 0) {
            return;
        }

        throw ValidationException::withMessages([
            'brand' => [
                "Cannot delete \"{$brand->name}\" because it is linked to {$count} product(s). Unlink products first.",
            ],
        ]);
    }

    /**
     * Ensure none of the given brands are linked to products.
     *
     * @param list<int> $ids
     *
     * @throws ValidationException
     */
    private function assertBrandsNotLinkedToProducts(array $ids): void
    {
        $brands = Brand::query()
            ->whereIn('id', $ids)
            ->withCount('products')
            ->get();

        $linked = $brands->filter(static fn (Brand $brand): bool => $brand->products_count > 0);

        if ($linked->isEmpty()) {
            return;
        }

        $details = $linked
            ->map(static fn (Brand $brand): string => "\"{$brand->name}\" ({$brand->products_count})")
            ->implode(', ');

        throw ValidationException::withMessages([
            'ids' => [
                "Cannot delete brands linked to products: {$details}. Unlink products first.",
            ],
        ]);
    }
}
